name: KitEngine
version: '${version}'

main: com.github.nightdev.kitEngine.KitEngine
api-version: '1.21'
load: POSTWORLD

authors: [ NightDevMC ]
website: https://youtube.com/@NightDevMC


commands:
  kit:
    description: Claim a specific kit!
  kits:
    description: Open the kits menu!
  kitadmin:
    description: Opens the admin editor for kits!

soft-depend:
  - Vault